# Generated by Django 4.2.7 on 2025-10-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('hora', models.TimeField(auto_now_add=True, verbose_name='Hora')),
                ('estado_anterior', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado Anterior')),
                ('estado_nuevo', models.CharField(max_length=100, verbose_name='Estado Nuevo')),
                ('tipo_cambio', models.CharField(max_length=50, verbose_name='Tipo de Cambio')),
                ('valor_numerico', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Numérico')),
                ('unidad', models.CharField(blank=True, max_length=20, null=True, verbose_name='Unidad')),
                ('fuente', models.CharField(choices=[('sensor', 'Sensor'), ('manual', 'Manual'), ('automatico', 'Automático')], default='sensor', max_length=20, verbose_name='Fuente')),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de Origen')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
                'ordering': ['-fecha', '-hora'],
            },
        ),
    ]
