# Generated by Django 4.2.7 on 2025-09-30 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sensors', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField(auto_now_add=True, verbose_name='Hora')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado')),
                ('tipo_cambio', models.CharField(max_length=50, verbose_name='Tipo de Cambio')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='sensors.sensor', verbose_name='Sensor')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros', to='users.user', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
                'indexes': [models.Index(fields=['fecha'], name='history_reg_fecha_a965d4_idx'), models.Index(fields=['sensor', 'fecha'], name='history_reg_sensor__cd57a1_idx'), models.Index(fields=['usuario', 'fecha'], name='history_reg_usuario_5b5307_idx')],
            },
        ),
    ]
