# Generated by Django 4.2.7 on 2025-10-01 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('history', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros', to='users.user', verbose_name='Usuario'),
        ),
        migrations.AddIndex(
            model_name='registro',
            index=models.Index(fields=['fecha'], name='history_reg_fecha_a965d4_idx'),
        ),
        migrations.AddIndex(
            model_name='registro',
            index=models.Index(fields=['-fecha', '-hora'], name='history_reg_fecha_49f54d_idx'),
        ),
        migrations.AddIndex(
            model_name='registro',
            index=models.Index(fields=['sensor', 'fecha'], name='history_reg_sensor__cd57a1_idx'),
        ),
        migrations.AddIndex(
            model_name='registro',
            index=models.Index(fields=['usuario', 'fecha'], name='history_reg_usuario_5b5307_idx'),
        ),
        migrations.AddIndex(
            model_name='registro',
            index=models.Index(fields=['tipo_cambio', 'fecha'], name='history_reg_tipo_ca_4dd27c_idx'),
        ),
        migrations.AddIndex(
            model_name='registro',
            index=models.Index(fields=['fecha', 'tipo_cambio'], name='history_reg_fecha_3ec994_idx'),
        ),
    ]
