# Generated by Django 4.2.7 on 2025-09-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Aula')),
                ('ip_esp32', models.GenericIPAddressField(unique=True, verbose_name='IP ESP32')),
                ('ultima_señal', models.DateTimeField(auto_now=True, verbose_name='Última Señal')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
                'indexes': [models.Index(fields=['ip_esp32'], name='classrooms__ip_esp3_1d2aab_idx')],
            },
        ),
    ]
