# Generated by Django 4.2.7 on 2025-10-01 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Aula')),
                ('ip_esp32', models.GenericIPAddressField(unique=True, verbose_name='IP ESP32')),
                ('ultima_señal', models.DateTimeField(blank=True, null=True, verbose_name='Última Señal')),
                ('timeout_inactividad', models.IntegerField(default=30, verbose_name='Timeout Inactividad (minutos)')),
                ('apagado_automatico', models.BooleanField(default=True, verbose_name='Apagado Automático')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apagado_automatico_habilitado', models.BooleanField(default=True, verbose_name='Apagado Automático Habilitado')),
                ('tiempo_inactividad_minutos', models.IntegerField(default=30, help_text='Tiempo sin movimiento antes de apagar luces', verbose_name='Tiempo de Inactividad (minutos)')),
                ('horario_laboral_solo', models.BooleanField(default=True, help_text='Solo apagar automáticamente durante horario laboral', verbose_name='Solo en Horario Laboral')),
                ('hora_inicio_laboral', models.TimeField(default='08:00', verbose_name='Hora Inicio Laboral')),
                ('hora_fin_laboral', models.TimeField(default='18:00', verbose_name='Hora Fin Laboral')),
                ('lunes_habilitado', models.BooleanField(default=True, verbose_name='Lunes')),
                ('martes_habilitado', models.BooleanField(default=True, verbose_name='Martes')),
                ('miercoles_habilitado', models.BooleanField(default=True, verbose_name='Miércoles')),
                ('jueves_habilitado', models.BooleanField(default=True, verbose_name='Jueves')),
                ('viernes_habilitado', models.BooleanField(default=True, verbose_name='Viernes')),
                ('sabado_habilitado', models.BooleanField(default=False, verbose_name='Sábado')),
                ('domingo_habilitado', models.BooleanField(default=False, verbose_name='Domingo')),
                ('tiempo_gracia_minutos', models.IntegerField(default=5, help_text='Tiempo adicional antes de apagar luces después de detectar movimiento', verbose_name='Tiempo de Gracia (minutos)')),
                ('maximo_apagados_por_dia', models.IntegerField(default=10, help_text='Límite de apagados automáticos por día (0 = sin límite)', verbose_name='Máximo Apagados por Día')),
                ('ultimo_apagado', models.DateTimeField(blank=True, null=True, verbose_name='Último Apagado Automático')),
                ('apagados_hoy', models.IntegerField(default=0, verbose_name='Apagados Hoy')),
                ('fecha_ultimo_reset', models.DateField(auto_now_add=True, verbose_name='Fecha Último Reset de Contador')),
                ('notificar_apagado', models.BooleanField(default=False, help_text='Enviar notificación cuando se ejecute apagado automático', verbose_name='Notificar Apagado')),
                ('aula', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion', to='classrooms.aula', verbose_name='Aula')),
            ],
            options={
                'verbose_name': 'Configuración de Aula',
                'verbose_name_plural': 'Configuraciones de Aulas',
            },
        ),
        migrations.AddIndex(
            model_name='aula',
            index=models.Index(fields=['ip_esp32'], name='classrooms__ip_esp3_1d2aab_idx'),
        ),
        migrations.AddIndex(
            model_name='aula',
            index=models.Index(fields=['ultima_señal'], name='classrooms__ultima__bc272b_idx'),
        ),
        migrations.AddConstraint(
            model_name='aula',
            constraint=models.UniqueConstraint(fields=('ip_esp32',), name='unique_ip_esp32'),
        ),
    ]
