# Generated by Django 4.2.7 on 2025-10-01 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classrooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('luz', 'Sensor de Luz'), ('movimiento', 'Sensor de Movimiento'), ('ventana', 'Sensor de Ventana'), ('rele', 'Relé')], max_length=20, verbose_name='Tipo de Sensor')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('estado_actual', models.CharField(blank=True, max_length=50, verbose_name='Estado Actual')),
                ('pin_esp32', models.IntegerField(verbose_name='Pin ESP32')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensores', to='classrooms.aula', verbose_name='Aula')),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensores',
            },
        ),
    ]
