# Generated by Django 4.2.7 on 2025-10-01 15:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_user', models.OneToOneField(on_delete=models.CASCADE, related_name='gestor_user', to=settings.AUTH_USER_MODEL)),
                ('legajo', models.CharField(max_length=20, unique=True, verbose_name='Legajo')),
                ('rol', models.CharField(choices=[('Admin', 'Administrador'), ('Operario', 'Operario')], default='Operario', max_length=10, verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
